#+STARTUP: showall indent hidestars

* Intro

Я хочу проанализировать структуру стейт-машин конвейера и результаты
разбора представить как plantuml-диаграмму.

Пока у меня есть один файл, который я хочу разобрать, по-видимому он
наиболее сложный из всех стейт-машин. Я считаю, что если я буду успешно
разбирать его, то и с остальными не будет никаких проблем.

#+NAME: filename
#+BEGIN_SRC go
  "src/github.com/insolar/assured-ledger/ledger-core/v2/logicrunner/sm_object/object.go"
#+END_SRC

Так как это константа времении компиляции, то я ее тут же и определю и
отправлю в блок констант, который будет определен в ~main~ несколько
позже.

#+BEGIN_SRC go :noweb yes :noweb-ref consts
  filename  = <<filename>>
#+END_SRC


Я буду передавать ~filename~ в функцию ~analyse~, которая и будет
выполнять всю работу. Она возвратит необходимый мне ~uml~, и может что-то
выводить (сайд-эффект), например, диагностические сообщения.

Таким образом ~main~ будет просто выводить возвращаемое значение
~analyse~. В дальнейшем мы можем передавать это возвращаемое значение в
plantuml-построитель, но пока мне удобнее видеть это в консоли.

Еще ~main~ содержит placeholder для структур, которые будут определены
позднее.

#+NAME: main
#+BEGIN_SRC go :tangle analyse.go :noweb yes
  package main

  import (
      "errors"
      "flag"
      "fmt"
      "go/ast"
      "go/parser"
      "go/token"
      "io/ioutil"
      "os"
      "path/filepath"
      "reflect"
      "strings"
  )

  <<structs>>

  func main () {
      path := flag.String("f", "", "Path to file")
      console := flag.Bool("c", false, "Print uml diagram to console")
      debug := flag.Bool("d", false, "Enable debug")
      flag.Parse()

      if *path == "" {
          fmt.Print("Error: Path to file is not specific\n")
          return
      }
      uml := analyse(*path, *debug)

      if *console {
          fmt.Printf("\n\n\n\n\n~~~~~~~~~~~~~~~~~\n%s", uml)
      }

      writeUml(*path, uml)
  }

  <<analyse>>
#+END_SRC

* Analyse

~Analyse~ формирует ~uml~, разбирая файл с с помощью ~ParseFile~. Если
~ParseFile~ не справляется, она возвращает ~nil~ и мы уходим в панику,
потому что больше ничего не можем сделать.

#+NAME: analyse
#+BEGIN_SRC go :noweb yes
  func isInSet (s1 []string, item string) bool {
      for i1 := range s1 {
          if s1[i1] == item {
              return true
          }
      }
      return false
  }

  // setDiff returns a new set with all the elements that exist in
  // the first set and don't exist in the second set
  func setDiff (s1 []string, s2 []string) []string {
      ret := []string{}
      for i1 := range s1 {
          if !isInSet(s2, s1[i1]) {
             ret = append(ret, s1[i1])
          }
      }
      return ret
  }

  func SetUniWoDup (s1 []string, s2 []string) []string {
      ret := s1
      for i2 := range s2 {
          if !isInSet(s1, s2[i2]) {
             ret = append(ret, s2[i2])
          }
      }
      return ret
  }

  func analyse(path string, debug bool) string {
      pf := ParseFile(path, debug)
      if nil == pf {
          panic("Cannot parse file " + path)
      }
      uml := "@startuml"
      pf.dbgmsg("\n\n:: ======= resource filename: %s", pf.filename)

      unvisited := []string{"Init"}
      visited   := []string{}

      for 0 < len(unvisited) {
          // uml += fmt.Sprintf("\n-vis: %s", visited)
          // uml += fmt.Sprintf("\n-uns: %s", unvisited)

          state := pf.states[unvisited[0]]
          visited = append(visited, state.Name)
          // uml += fmt.Sprintf("\n:state.Migr:[%s]", state.Migr)

          pf.dbgmsg("\n\nfn: %s", state.Name) // Function name
          // pf.dbgmsg("\nrecv: %s | %s", state.Recv.Name, state.Recv.Type) // Receiver
          for parName, parType := range state.Pars { // Parameters
              pf.dbgmsg("\npar name: %s | type: %s", parName, parType)
          }

          // curr_migr propagate migration to outgoing arrows
          var possible_migrations []string = nil // Возможные миграции в этом состоянии
          // uml += fmt.Sprintf("\n:%s.Migr: [%s]", state.Name, state.Migr)
          if "NIL" == state.Migr { // Если миграции явно обнулены - никакие миграции не возможны
              possible_migrations = nil
              uml += fmt.Sprintf("\n%s : %s", state.Name, "NIL")
          } else if "" != state.Migr { // Если явно установлена миграция - возможна только она
              possible_migrations = []string{state.Migr}
          } else { // иначе берем унаследованные миграции
              uml += fmt.Sprintf("\n%s : %s", state.Name, "INHERITED")
              possible_migrations = state.Prop
          }

          for _, pos_migr := range possible_migrations {
              uml += fmt.Sprintf("\n%s : %s", state.Name, pos_migr)
              uml += fmt.Sprintf("\n%s -[#blue]-> %s", state.Name, pos_migr)
              if !isInSet(visited, pos_migr) {
                  unvisited = append(unvisited, pos_migr)
              }
          }

          for _, ret := range state.Rets {
              // uml += fmt.Sprintf("\n%s -[#green]-> %s", state.Name, ret)

              pf.dbgmsg("\n%s: ['%s']", ret.Lvl, ret.Str)
                pf.dbgmsg("\nfun: ['%s']\nobj: ['%s']", ret.Var.Fun, ret.Var.Obj)
                // dbg
                // uml += fmt.Sprintf("\n ! %s | %s", ret.StepMigration, ret.Var.Fun)
                switch ret.Var.Fun {
                case "Stop":
                    uml += fmt.Sprintf("\n%s --> [*]", state.Name)
                case "Jump", "ThenJump":
                    uml += fmt.Sprintf("\n%s --> %s : %s", state.Name, ret.Args[0].Fun, ret.Var.Fun)
                    unvisited = append(unvisited, ret.Args[0].Fun)
                    if nil != possible_migrations {
                        pf.states[ret.Args[0].Fun].Prop = SetUniWoDup(pf.states[ret.Args[0].Fun].Prop, possible_migrations)
                    }
                case "JumpExt":
                    uml += fmt.Sprintf("\n%s --> %s : %s", state.Name, ret.Args[0].Fun, ret.Var.Fun)
                    unvisited = append(unvisited, ret.Args[0].Fun)
                    uml += fmt.Sprintf("\n%s -[#DarkGreen]-> %s : %s+(StepMigration)", state.Name, ret.StepMigration, ret.Var.Fun)
                    unvisited = append(unvisited, ret.StepMigration)
                case "ThenRepeat":
                    uml += fmt.Sprintf("\n%s --> %s : ThenRepeat", state.Name, state.Name)
                case "RepeatOrJumpElse":
                    uml += fmt.Sprintf("\n%s -[#RoyalBlue]-> %s : RepeatOr(Jump)Else", state.Name, ret.Args[2].Fun)
                    uml += fmt.Sprintf("\n%s -[#DarkGreen]-> %s : RepeatOrJump(Else)", state.Name, ret.Args[3].Fun)
                default:
                    pf.dbgmsg("\n(=> (. %s %s)", ret.Var.Obj, ret.Var.Fun)
                    for _, arg := range ret.Args {
                        pf.dbgmsg("\n       %s", fmt.Sprintf("(. %s %s)", arg.Obj, arg.Fun))
                    }
                    pf.dbgmsg(")")
                }

                // -:- fn representation
                pf.dbgmsg(fmt.Sprintf("\n(-> (. %s %s)", ret.Var.Obj, ret.Var.Fun))

                for _, arg := range ret.Args {
                    pf.dbgmsg("\n       %s", fmt.Sprintf("(. %s %s)", arg.Obj, arg.Fun))
                }
                pf.dbgmsg(")")
          }
          unvisited = setDiff(unvisited, visited)
      }

      state_keys := make([]string, 0, len(pf.states))
      for k := range pf.states {
          state_keys = append(state_keys, k)
      }

      uml += "\n@enduml\n"
      return uml
  }

  <<write_uml>>

  <<parse_file>>
#+END_SRC

* Write UML

#+NAME: write_uml
#+BEGIN_SRC go
  func writeUml(path string, uml string) {
      name := filepath.Base(path)
      name = strings.Replace(name, ".go", "", -1) + ".plantuml"
      umlPath := fmt.Sprintf("%s/%s", filepath.Dir(path), name)

      file, err := os.Create(umlPath)
      if err != nil {
          fmt.Printf("%s Failed to create file: %s \n", err.Error(), umlPath)
          return
      }

      defer file.Close()

      _, err = file.WriteString(uml)
      if err != nil {
          fmt.Printf("Failed to write file: %s\n", umlPath)
          return
      }

      err = file.Sync()
      if err != nil {
          fmt.Printf("Failed to sync file: %s\n", umlPath)
          return
      }

      fmt.Printf("Uml saved: %s\n", umlPath)
  }
#+END_SRC

* ParseFile

Задача функции ~ParseFile~ - прочитать файл с помощью ~slurpFile~,
разобрать его и для каждой найденной внутри него функции вызвать
~pf.parseMethod~.

Функия ~ParseFile~ вовзращает объект ~ParsedFile~, который содержит все
разобранные функции и будет использоваться для анализа преобразованного
содержимого и построения ~uml~.

#+NAME: parse_file
#+BEGIN_SRC go :noweb yes
  func ParseFile(path string, dbg ...bool) *ParsedFile {
      pf := &ParsedFile{
          filename: path,
          dbg:      dbg[0],
      }

      sourceCode, err := slurpFile(path)
      if err != nil {
          fmt.Printf("Failed to slurpFile file: %s %s\n", path, err.Error())
          return nil
      }
      pf.code = sourceCode

      pf.fileSet = token.NewFileSet()
      node, err := parser.ParseFile(pf.fileSet, pf.filename, pf.code, parser.ParseComments)
      if err != nil {
          fmt.Printf("Failed to parse file: %s\n", path)
          return nil
      }
      pf.node = node

      pf.states = make(map[string]*FnState)

      ast.Inspect(node, func(n ast.Node) bool {
          fn, ok := n.(*ast.FuncDecl)
          if ok {
              pf.parseMethod(fn)
          }
          return true
      })

      return pf
  }

  <<slurp_file>>

  <<parse_method>>
#+END_SRC

Потребуется несколько вспомогательных определений и функций:

** ParsedFile stuct

Это структура, которая хранит все что мы смогли извлечь из кода
файла. Она содержит:
- dbg - флаг вывода диагностических сообщений
- filename - путь к файлу
- code - строку, содержащую весь код
- fileSet - set of source files для конкурентного доступа
- node - корневую ноду кода
- states - извлеченные состояния стейт-машины

#+BEGIN_SRC go :noweb-ref structs
  type ParsedFile struct {
      dbg      bool
      filename string
      code     []byte
      fileSet  *token.FileSet
      node     *ast.File
      states   map[string]*FnState
  }

#+END_SRC

** FnState struct

Это структура, которая представляет найденное состояние стейт машины. Она
содержит:
- Name - имя состояния
- Recv - объект к которому относится состояние (оставлен на случай если у
  нас вдруг в одном файле окажутся две стейт-машины)
- Pars - параметры, которые принимает функция состояния
- Rets - Все возможные возвращаемые значения, которые удалось найти
- Migr - Если внутри состояния есть вызов SetDefaultMigration, то тут
  будет его target
- Prop - temp var of migration for propagation to next states

#+BEGIN_SRC go :noweb-ref structs
  type FnState struct {
      Name string            // Name of function
      Recv *RecvPair         // Receiver
      Pars map[string]string // Parameters: k:name, v:type
      Rets []*Ret            // All returns
      Migr string            // Target from SetDefaultMigration or empty
      Prop []string
  }

#+END_SRC

** RecvPair stuct

Эта структура содержит данные ресейвера к которому относится состояние
стейт-машины:
- имя
- тип

#+BEGIN_SRC go :noweb-ref structs
  type RecvPair struct {
      Name string
      Type string
  }

#+END_SRC

** Ret struct

Эта структура содержит "выходы состояния", которые удалось найти при
парсинге этого состояния. Содержит:
- Lvl - глубина в коде (Top или Deep)
- Str - строковое представление выхода
- Type - тип возвращаемого значения из списка типов возвращаемых
  значений, определенных в ... [TODO:gmm]
- Var - содержимое возвращаемого значения
- Args - аргументы (если есть)
- StepMigration - особый случай для JumpExt, когда миграция заменяется на
  один шаг

#+BEGIN_SRC go :noweb-ref structs
  type Ret struct {
      Lvl  string
      Str  string
      Var  Variant
      Args []Variant
      StepMigration string
  }

#+END_SRC

** Variant struct

Variant - это структура, которая представляет [TODO:gmm]

#+NAME: variant
#+BEGIN_SRC go :noweb-ref structs
  type Variant struct {
      Obj  string
      Fun  string
      Str  string // string representation
  }

#+END_SRC

** SlurpFile

Это функция, которая считывает файл

#+NAME: slurp_file
#+BEGIN_SRC go
  func slurpFile(filename string) ([]byte, error) {
      file, err := os.OpenFile(filename, os.O_RDONLY, 0)
      if err != nil {
          return nil, errors.New(fmt.Sprintf("Can't open file: [%s], %s\n", filename, err.Error()))
      }
      defer file.Close() //nolint: errcheck

      res, err := ioutil.ReadAll(file)
      if err != nil {
          return nil, errors.New(fmt.Sprintf("Can't read file: [%s]\n", filename))
      }
      return res, nil
  }
#+END_SRC

* ParseMethod

Здесь я разбираю каждую функцию в файле и анализирую ее. Если
анализируемая функция не имеет ~receiver~ - она не является методом, и
тогда ее можно пропустить - такие функции нас не интересуют.

В ином случае я начинаю анализировать function declaration.

На этапе анализа function declaration мы итерируемся по receivers,
несмотря на то что он там один - в какой-то момент так оказалось удобнее.

Небольшое отступление: Для целей отладки я бы хотел иметь способ кратко
выводить диагностические сообщения. Для этого я сделал
раздел [[*Diag][Dbgmsg]] в котором описана одноименная функция.

#+NAME: parse_method
#+BEGIN_SRC go :noweb yes
  func (pf *ParsedFile) parseMethod(fn *ast.FuncDecl) {

      // I want to analise only method functions (if exists)
      if nil == fn.Recv {
          pf.dbgmsg("\n:parseMethod: skip %s - No receiver", fn.Name.Name)
      } else {
          for _, fld := range fn.Recv.List {
              pf.parseRecv(fn, fld)
          }
      }
  }

  <<parse_recv>>

  <<dbgmsg>>

  <<is_method_takes_ctx>>

  <<collect_rets>>
#+END_SRC

** Parse Recv

Далее я выделяю из декларации функции:
- пару Name:Type receiver-a
- хэшмап с параметрами, где ключи - имена параметров, а значения - их
  типы

На этом этапе уже можно определить, принимает ли метод
параметр-контекст. Если нет - то такой метод нас не интересует и мы можем
его пропустить. Пропуск осуществляется как простой возврат из функции
~ParseRecv~. Я определяю есть ли контекст с помощью функции
~isMethodTakesCtx~ которая описана ниже в подразделе.

Аналогичным образом я отфильтровываю методы, которые не возвращают
значений, потому что среди состояний SM таких быть не может.

Более того, меня интересуют только такие методы, которые возвращают
значение типа ~smashine.StateUpdate~

Окей, на этом этапе у меня есть интересующие методы - можно вывести их
имена и перейти к разбору их кода. Я ищу все возвращаемые значения и
сохраняю их в переменную ~rets~. Мне также пришлось написать функцию
~collectRets~, потому что это оказалось нетривиально (см. ниже в
подразделе)

Теперь у меня есть все данные и я сохраняю их в хэш-мапу ~pf.states~, где
ключом является имя состояния, а значением тип FnState, содержащий:
- Name
- Recv
- Pars
- Rets

#+NAME: parse_recv
#+BEGIN_SRC go :noweb yes
  func (pf *ParsedFile) parseRecv(fn *ast.FuncDecl, fld *ast.Field) {

      // Receiver
      recv := &RecvPair{
          Name: fld.Names[0].Name,
          Type: fmt.Sprintf("%s", pf.code[fld.Type.Pos()-1:fld.Type.End()-1]),
      }

      // Parameters
      pars := make(map[string]string, 0)
      name := "unnamed-param"
      for _, par := range fn.Type.Params.List {
          if nil != par.Names {
              name = par.Names[0].Name
          }
          pars[name] = fmt.Sprintf("%s", pf.code[par.Type.Pos()-1:par.Type.End()-1])
      }


      // I want to analyse only methods, who takes context
      if !isMethodTakesCtx(pars) {
          pf.dbgmsg("\n:parseMethod: skip %s - Doesn`t take CTX", fn.Name.Name)
          return
      }

      // I want analyse only methods, which returned values
      if nil == fn.Type.Results {
          pf.dbgmsg("\n:parseMethod: skip %s - No return value", fn.Name.Name)
          return
      }

      // I want to analyze methods which have a `smashine.StateUpdate' result type
      res := fn.Type.Results.List[0].Type
      resSel, ok := res.(*ast.SelectorExpr)
      if !ok || "StateUpdate" != resSel.Sel.Name {
          if pf.dbg {
              fmt.Printf("\n:parseMethod: skip %s - No StateUpdate result type", fn.Name.Name)
          }
          return
      }
      resXstr := fmt.Sprintf("%s", pf.code[resSel.X.Pos()-1:resSel.X.End()-1])
      if "smachine" != resXstr {
          if pf.dbg {
              fmt.Printf("\n:parseMethod: skip %s - No smachine selector result type", fn.Name.Name)
          }
          return
      }

      // Show name (debug)
      pf.dbgmsg("\n:parseMethod: (sm-name) %s", fn.Name.Name)

      // Find all Return Statements and SetDefaultMigration calls
      var rets = make([]*Ret, 0)
      var migr = ""
      for _, smth := range fn.Body.List { // ∀ fn.Body.List ← (or RetStmt (Inspect ...))
          retStmt, ok := smth.(*ast.ReturnStmt)
          if ok {
              // return from top-level statements of function
              rets = append(rets, pf.collectRets(retStmt, "Top")...)
          } else {
              ast.Inspect(smth, func(in ast.Node) bool {
                  // Find Return Statements
                  retStmt, ok := in.(*ast.ReturnStmt) // ←
                  if ok {
                      // return from deep-level function statememt
                      rets = append(rets, pf.collectRets(retStmt, "Deep")...)
                  } else {
                      migr = pf.findSetDefaultMigration(migr, in)
                  }
                  return true
              })
          }
      }

      pf.states[fn.Name.Name] = &FnState{
          Name: fn.Name.Name,
          Recv: recv,
          Pars: pars,
          Rets: rets,
          Migr: migr,
      }
  }

  func (pf *ParsedFile) findSetDefaultMigration (migr string, in ast.Node) string {
      // Find "ctx.SetDefaultMigration(some_target)"
      stmt, ok := in.(*ast.ExprStmt)
      if ok {
          callexpr, ok := stmt.X.(*ast.CallExpr)
          if ok {
              selexpr, ok := callexpr.Fun.(*ast.SelectorExpr)
              if ok {
                  selexpr_x, ok := selexpr.X.(*ast.Ident)
                  if ok {
                      if (("ctx" == selexpr_x.Name) &&
                          ("SetDefaultMigration" == selexpr.Sel.Name)) {
                          for _, arg := range callexpr.Args {
                              argsel, ok := arg.(*ast.SelectorExpr)
                              if ok {
                                  pf.dbgmsg(fmt.Sprintf("\n>>>:[%s]", argsel.Sel.Name))
                                  migr = argsel.Sel.Name
                              }
                              argnil, ok := arg.(*ast.Ident)
                              if ok {
                                  pf.dbgmsg(fmt.Sprintf("\n>>>:[%s]", argnil))
                                  migr = "NIL"
                              }
                          }
                      }
                  }
              }
          }
      }
      return migr
  }
#+END_SRC

** Dbgmsg

Если ~pf.dbg==true~ - выводит диагностическое сообщение

#+NAME: dbgmsg
#+BEGIN_SRC go
  func (pf *ParsedFile) dbgmsg(msg string, par ...interface{}) {
      if pf.dbg {
          fmt.Printf(msg, par...)
      }
  }
#+END_SRC

** isMethodTakesCtx

Функция определяет есть ли в хэш-мапе параметров какой-нибудь параметр,
который содержит "Context" в названии своего типа.

#+NAME: is_method_takes_ctx
#+BEGIN_SRC go
  func isMethodTakesCtx(pars map[string]string) bool {
      for _, parType := range pars {
          if strings.Contains(parType, "Context") {
              return true
          }
      }
      return false
  }
#+END_SRC

** collectRets

Эта функция анализирует переданный ей ~return statement~. Во всех случаях
которые мне встретились эти return statement имеют тип ~*ast.CallExpr~,
но я на всякий случай делаю CASE по типу, т.к. неизвестно что может
встретиться в будущем.

Существуют простые return statements, вроде ~ctx.Stop()~ или
~ctx.Jump(smth)~.



Более сложные случаи - это варианты ~ctx.JumpExt~, которые выглядят так:

#+BEGIN_SRC go
  ctx.JumpExt(smachine.SlotStep{
      Transition: sm.waitForMigration,
      Migration:  sm.migrateSendStateAfterExecution,
  })
#+END_SRC



И наконец, наиболее объемные вот такие простыни:

#+BEGIN_SRC go
  sm.artifactClient.PrepareAsync(ctx, func(svc s_artifact.ArtifactClientService) smachine.AsyncResultFunc {
		...
		return func(ctx smachine.AsyncResultContext) {
            ...
		}
	}).DelayedStart().Sleep().ThenJump(sm.stateGotLatestValidatedStatePrototypeAndCode)
#+END_SRC

Как можно заметить, все они представляют собой т.н. ~SelectorExpr~, т.е
выражение с точкой. То, что после точки называется ~Selector~ и во всех
встреченных случаях представляе собой что-то из этого списка:
- Stop
- Jump
- ThenRepeat
- ThenJump
- JumpExt
Я сохраняю это в ~item.Var.Fun~ (Var - потому что Variant, Fun - потому
что это функция (вернее метод) вызываемая на объекте)

А вот то, что идет до точки называется ~X~ и может быть разных типов:
- *ast.Ident - как правило это ~ctx~, это характерно для возвратов вида:
  - ctx.Stop()
  - ctx.Jump(smth)
  - ctx.JumpExt(SlotStep) - в этом случае внутри будет структура
    SlotStep, указывающая на миграцию (об этом позже в этом разделе)
- *ast.CallExpr - это варианты:
  - ctx.Sleep().ThenRepeat()
  - someasync.DelayedStartSleep().ThenJump(smth)
~X~ превращается в свое строковое представление и сохраняется в
~item.Var.Obj~. Здесь можно было бы добавить дополнительный разбор его на
составляющие, но более ценную информацию можно получить из аргументов
~return statement CallExpr~ (и ее пока хватает для устранения любых
неоднозначностей)

Поэтому, сейчас мы переходим к разбору этих аргументов.

Аргументы бывают разных типов:
- отсутствующий аргумент не имеет типа, например в ~ctx.Stop()~,
  ~ctx.Sleep()~, ~ctx.ThenJump()~ или ~ctx.Sleep().ThenRepeat()~
- ~*ast.SelectorExpr~ - это как правило ~target~ для
  ~ctx.Jump(sm.target)~
- ~*ast.CompositeLit~ - встречается только ~ctx.JumpExt(SlotStep)~,
  содержит Transition и Migration. Transition - это собственно переход, а
  Migration заменяет текущую миграцию, но только на один шаг. Я пока
  сохраняю Transition в переход, а Migration - в ~item.StepMigration~

#+NAME: collect_rets
#+BEGIN_SRC go
  func (pf *ParsedFile) collectRets(retStmt *ast.ReturnStmt, level string) []*Ret {
      var acc []*Ret
      for _, ret := range retStmt.Results {
          item := &Ret{
              Lvl: level,
              Str: fmt.Sprintf("%s", pf.code[ret.Pos()-1:ret.End()-1]),
          }
          pf.dbgmsg("\n :collectRet: ~~~~~~ (item.Str) : %s",  item.Str)

          for _, retNode := range retStmt.Results {
              switch retNode.(type) {
              case *ast.CallExpr:
                  retCall := retNode.(*ast.CallExpr)
                  switch retCall.Fun.(type) {
                  case *ast.SelectorExpr:
                      retSelector := retCall.Fun.(*ast.SelectorExpr)
                      item.Var.Fun = retSelector.Sel.Name
                      pf.dbgmsg("\n  :collectRet: (Selector) (%s.) =:[%s]:=", reflect.TypeOf(retSelector.X), retSelector.Sel.Name)
                      switch retSelector.X.(type) { // Analyse started from [selector.*]
                      case *ast.Ident:
                          retX := retSelector.X.(*ast.Ident)
                          item.Var.Obj = retX.Name
                          pf.dbgmsg("\n   :collectRet: (ident) : %s _._", item.Var.Obj)
                          switch item.Var.Fun {
                          case "Jump", "Stop", "JumpExt":
                          default:
                              pf.dbgmsg("\n:collectRets: [WARN]: UNKNOWN RET SELECTOR '%s' in '%s.%s'",
                                  item.Var.Fun, item.Var.Obj, item.Var.Fun)
                          }
                      case *ast.CallExpr:
                          subX := retSelector.X.(*ast.CallExpr)
                          subXStr := fmt.Sprintf("%s", pf.code[subX.Pos()-1:subX.End()-1])
                          item.Var.Obj = subXStr
                          pf.dbgmsg("\n   :collectRet: (call to selector) : %s _._", item.Var.Obj)
                          switch item.Var.Fun { // Check Fun (nb: not arg!)
                          case "ThenRepeat", "ThenJump":
                          default:
                              fmt.Printf("\n:collectRets: [WARN]: UNKNOWN RET SUB SELECTOR '%s' in '%s'",
                                  item.Var.Fun, item.Var.Obj, item.Var.Fun)
                          }
                      default:
                          fmt.Printf("\n:collectRets: [ERR]: UNKNOWN RETSELECTOR %s | ",
                              reflect.TypeOf(retSelector.X),
                              pf.code[retSelector.X.Pos()-1:retSelector.X.End()-1],
                          )
                      }

                      // Args
                      accArgs := make([]Variant, 0)
                      for _, retarg := range retCall.Args {
                          pf.dbgmsg("\n   -:collectRet: arg type [%s]", reflect.TypeOf(retarg))
                          switch retarg.(type) {
                          case *ast.SelectorExpr:
                              sel := retarg.(*ast.SelectorExpr)
                              selName := fmt.Sprintf("%s", pf.code[sel.X.Pos()-1:sel.X.End()-1])
                              pf.dbgmsg("\n   -|[%s] %s .|. %s", reflect.TypeOf(sel), selName, sel.Sel.Name)
                              arg := Variant{
                                  Obj:  selName,
                                  Fun:  sel.Sel.Name,
                              }
                              accArgs = append(accArgs, arg)
                          case *ast.CompositeLit:
                              cl := retarg.(*ast.CompositeLit)
                              // We know only JumpExt composite literal
                              arg := Variant{}
                              if "JumpExt" == item.Var.Fun {
                                  ast.Inspect(cl, func(n ast.Node) bool {
                                      exp, ok := n.(*ast.KeyValueExpr)
                                      if ok {
                                          keystr := fmt.Sprintf("%s", exp.Key)
                                          switch keystr {
                                          case "Transition":
                                              sel := exp.Value.(*ast.SelectorExpr)
                                              selName := fmt.Sprintf("%s", pf.code[sel.X.Pos()-1:sel.X.End()-1])
                                              arg = Variant{
                                                  Obj:  selName,
                                                  Fun:  sel.Sel.Name,
                                              }
                                              pf.dbgmsg("\n   -| -transition: %s.%s", selName, sel.Sel.Name)
                                          case "Migration":
                                              sel := exp.Value.(*ast.SelectorExpr)
                                              selName := fmt.Sprintf("%s", pf.code[sel.X.Pos()-1:sel.X.End()-1])
                                              item.StepMigration = sel.Sel.Name
                                              // arg = Variant{
                                              //     Type: SelectorType,
                                              //     Obj:  selName,
                                              //     Fun:  sel.Sel.Name,
                                              // }
                                              pf.dbgmsg("\n   -| --migration: %s.%s", selName, sel.Sel.Name)
                                          default:
                                              pf.dbgmsg("\n:collectRets: [ERR]: UNKNOWN keystr [%s]", keystr)
                                          }
                                      }
                                      return true
                                  }) // end of Inspect
                              } else {
                                  pf.dbgmsg("\n:collectRets: [ERR]: UNK JumpExt transition")
                              }
                              accArgs = append(accArgs, arg)
                          default:
                              pf.dbgmsg("\n:collectRets: [ERR]: UNKNOWN RETARGtype [%s] :OF: %s", reflect.TypeOf(retarg), retarg)
                          }
                      } // end of args
                      item.Args = accArgs
                  default:
                      pf.dbgmsg("\n:collectRets: [ERR]: UNKNOWN RETSEL %s", fmt.Sprintf("%s", reflect.TypeOf(retCall.Fun)))
                  }
              default:
                  pf.dbgmsg("\n [ERR]: UNKNOWN TYPE OF RETNODE %s", fmt.Sprintf("%s", reflect.TypeOf(retNode)))
              } // end of switch retnode type
          }
          acc = append(acc, item)
      }
      return acc
  }
#+END_SRC

* Object architecture

Первой строчкой в ~Init~ идет
~ctx.SetDefaultMigration(sm.migrateSendStateBeforeExecution)~ Теперь,
если пульс сменится - то будет переход в это состояние.

Миграции могут произойти только во время того когда машина не
исполняется, т.е. между состояниями.

Поэтому если пульс сменится, то мы окажемся в состоянии
~migrateSendStateBeforeExecution~, где первым делом вызывается
~ctx.SetDefaultMigration(nil)~, (что запрещает миграции, если пульс
сменится снова, я так понимаю) а потом следует переход в
~stateSendStateBeforeExecution~.  Я не понимаю зачем нужен этот переход,
потому что можно было включить это состояние в предыдущее и это ничего не
поменяло бы.

Тем не менее, мы посылаем ExecutorResults на VE с новым состоянием,
зависящим от sm.PreviousExecutorState (не понимаю зачем) и делаем
~Stop~ - на этом ветка со сменой пульса сразу после Init-а завершается.

Таким образом, при сборке UML нужно показать что из состояния где есть
вызов ~SetDefaultMigration~ есть перезод в состояние, которое является
аргумент-ом ~SetDefaultMigration~, кроме тех случаев, когда этот
аргумент - nil. Что будет если в таком случае в этот момент придет смена
пульса?


Если же пульс не меняется, то из ~Init~-a мы переходим в
~stepCheckPreviousExecutor~.

В ~sm~ есть ~PreviousExecutorState~ по которому мы свитчимся и отсюда
есть три перехода:
- stepGetPendingsInformation
- Repeat
- stepGetLatestValidatedState




в migrateStop мы попадаем из “stepGetLatestValidatedState”
2:36
после выхода из (!!)

stateGotLatestValidatedStatePrototypeAndCode

включается

migrateSendStateAfterExecution
